# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'https-rhdsmnd-github-io'

google-ID: 'UA-112060364-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/rondesmond1'}
- {icon: 'envelope', link: 'mailto:rhdsmnd@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
